version: '3.9'

services:
  django:
      image: ocl-docker:latest
      ports:
        - "8000:8000"
      env_file: .env

  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: .env
    command: gunicorn oc_lettings_site.wsgi.application --bind 0.0.0.0:5000
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db

  db:
    container_name: dev_db
    image: busybox
    env_file: .env
    volumes:
      - ./data:/data

volumes:
  data:
  static_volume:
