# Generated by Django 3.0 on 2023-08-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='lettings_address',
        ),
    ]
