version: 2.1 

orbs:
  docker: circleci/docker@2.1.3
  python: circleci/python@2.0.3
  heroku: circleci/heroku@2.0.0

jobs:
  run-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: pytest

  build-push-docker:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command:
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Connect to Docker Hub
          command:
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run:
          name: Push docker image
          command:
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 gremy44/$IMAGE_NAME:$CIRCLE_SHA1 |
            docker push gremy44/$IMAGE_NAME:$CIRCLE_SHA1

  deploye-from-dockerhub-to-heroku:
    docker:
      - image: $IMAGE_NAME:$CIRCLE_SHA1
    steps:
      - checkout
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

  # deploye-on-heroku:
    # docker:
      # - image: cimg/base:stable
    # steps:
      # - checkout
      # - setup_remote_docker
      # - heroku/install
      # - run:
          # name: Heroku
          # command: |
            # echo $DSN_SENTRY
            # curl https://cli-assets.heroku.com/install.sh | sh
            # HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            # HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -a $HEROKU_APP_NAME
            # HEROKU_API_KEY=${HEROKU_API_KEY} heroku config:set DSN_SENTRY=$DSN_SENTRY -a $HEROKU_APP_NAME
            # HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a $HEROKU_APP_NAME web
            # HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a $HEROKU_APP_NAME web

workflows:
  version: 2
  run_tests_and_build_docker:
    jobs:
      - run-test
      - build-push-docker:
          filters:
            branches:
              only: main
          requires:
            - run-test
      - deploye-from-dockerhub-to-heroku:
          filters:
            branches:
              only: main
          requires:
            - build-push-docker
      # - deploye-on-heroku:
          # filters:
            # branches:
              # only: main
          # requires:
            # - run-test
