version 2.1

# on créé l'orbs
# packages réutilisables de configuration et d'automatisation prédéfinis

orbs:
  python: circleci/python@1.5.0

# on créé les jobs qui sont les tâches à effectuer
jobs:

  # le premier, quand je push sur develop on lance les tests

  run-test:
    docker:
      # je prend l'image de python 3.10.2 pour faire mes tests circle ci
      # environnement de tests tout ca tout ca 
      - image: cimg/python:3.10.2

    steps:
      # duplication du repo
      - checkout
      # installation des packages
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      # lancement des tests
      - run:
          name: Run tests
          command: pytest

  # le deuxième, quand je pull request sur main on lance le déploiement
  build_and_push_docker:
    docker:
      - image: python:latest  # !!!Assurez-vous d'utiliser la version de Docker appropriée
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  # Cachez les couches Docker pour accélérer la construction si nécessaire
      - run:
          name: Build and Push Docker Image
          command: |
            # Construisez votre image Docker ici
            docker build -t ocl-docker .
            # Poussez l'image vers Docker Hub (ou un autre registre)
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker tag ocl-docker $DOCKER_HUB_USERNAME/ocl-docker:latest
            docker push $DOCKER_HUB_USERNAME/ocl-docker:latest

workflows:
  version: 2
  run_tests_and_build_docker:

    jobs:
      - run_tests:
          context: my-context  # Remplacez par le contexte approprié pour vos secrets
        filters:
          branches:
            only:
              - develop  # Exécutez ce job lorsque vous poussez sur la branche develop

      - build_and_push_docker:
          context: my-context  # Remplacez par le contexte approprié pour vos secrets
        filters:
          branches:
            only:
              - main  # Exécutez ce job lorsque vous créez une pull request de develop vers main

    environment:
      MY_SENSITIVE_VARIABLE:
        value: $DOCKER_HUB_PASSWORD
        masked: true